### ISSUE TITLE
[BUG] Screen.display_at() cannot display after the board has been displayed

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#104]
**Describe the bug**
Screen.display_at() cannot display after the board has been displayed

**To Reproduce**
1. Display a board
2. try to display something under the board with Screen.display_at()

**Expected behavior**
display_at() should be able to display anywhere on screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux 31
 - Python version 3.7.8

**Additional context**

**Comment by MChlebowski** [comment]
Can you assign this issue to me, please?

**Comment by MChlebowski** [comment]
Also please explain the exact behavior you expect. Should the messages be visible over the board all the time until explicitly removed or only until the board is refreshed?

**Comment by arnauddupuis** [comment]
I assigned it to you.
It is extremely easy to replicate. I discovered it during the development of [Mytonica](https://github.com/arnauddupuis/mytonica). If you look at the [mytonica.py](https://github.com/arnauddupuis/mytonica/blob/3a698b451481fd9a345dff5f9e11abdd7f3a7a23/mytonica.py#L657) file, the redraw_screen() function display the board and also all the other graphic elements (like the cell box or the command box).
It uses a mix of Screen.display_at() and Screen.display_line() (it also uses a [draw_box()](https://github.com/arnauddupuis/mytonica/blob/3a698b451481fd9a345dff5f9e11abdd7f3a7a23/mytonica.py#L601) function but this is just packing special logic for box drawing in an handy function).
If you look carefully anything that is displayed under the board is using Screen.display_line() because Screen.display_at() would not display the text at the right position (or at all). I do not know why, I suspect that I'm either missusing the contexts from the Terminal module or that I have some aggressive cleaning done somewhere, but I haven't look into this yet.

The expected behavior is that display_at() displays everywhere on the screen no matter the position of the board

**Comment by arnauddupuis** [comment]
Investigating a bit and wanting to give you a more concise example, I wrote that:
```python
from pygamelib import engine, board_items, constants


def update(g, inkey, dt):
    g.screen.display_line(f"This is BEFORE Board.display()")
    g.screen.display_at("test 0", 5, g.current_board().width + 20, flush=True)
    g.current_board().display()
    g.screen.display_at("test 1", 5, g.current_board().width + 20, flush=True)
    if inkey == "x":
        g.state = constants.STOPPED
    elif inkey == "w":
        g.move_player(constants.UP)
    elif inkey == "s":
        g.move_player(constants.DOWN)
    elif inkey == "a":
        g.move_player(constants.LEFT)
    elif inkey == "d":
        g.move_player(constants.RIGHT)
    g.screen.display_at("test 2", 10, g.current_board().width + 20)
    g.screen.display_at("test 3", g.current_board().height + 3, 2, flush=True)
    g.screen.display_at("test 4", g.current_board().height + 5, 2, flush=True)
    g.screen.display_at("test 5", 0, 2, flush=True)
    g.screen.display_line(f"This is AFTER Board.display()")


game = engine.Game(user_update=update, mode=constants.MODE_RT)
game.player = board_items.Player()
game.add_board(1, engine.Board())
game.change_level(1)
game.screen.clear()
game.run()
```

And in my case (Konsole/zsh) test 0 and test 4 do not display.
