### ISSUE TITLE
Remove legacy files

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#105]
**Problem summary/missing feature:**  
The change of name from hac-game-lib to pygamelib required deprecating the hac-game-lib module and that required some extra files. It is time to clean that up.

**Expected behavior:**  
Remove the extra files

**Work to do:**  
Remove the following files:

- [ ] Readme-Legacy.md
- [ ] setup-legacy.py

**Comment by Frans06** [comment]
Assign this too me

**Comment by arnauddupuis** [comment]
Done
