### ISSUE TITLE
Use Sprixels instead of models in pgl-editor

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#110]
**Problem summary/missing feature:**  
In the editor, when a user creates an item and places it on the board, the item uses the "traditional" system affecting a model through:
```python
item.model = a_model
```
With the introduction of the Sprixel object in v1.2 the editor should switch the default behavior to using sprixels:
```python
item.sprixel = Sprixel(a_model)
```

This would also allow for color changing, background pseudo-transparency, and all other benefits from sprixels.

**Work to do:**  
This issue requires to:

- [ ] Change the item creation process in pgl-editor to use Sprixels.
- [ ] Make sure that the Game.save_board() method correctly saves the items with the Sprixel in the board file.
- [ ] Make sure that the Game.load_board() method correctly load the board file and make use of the Sprixel.
- [ ] Make sure that there is no non-anticipated side effects.

**Comment by ollelogdahl** [comment]
Hello, i would like to contribute to this. Looking into the feature right now! :)

**Comment by arnauddupuis** [comment]
Cool! I'll assign it to you.
It is a good feature to quickly get your hands dirty ;)
If you need any help, please ask me.
