### ISSUE TITLE
Fix the inheritance graph

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#111]
**Problem summary/missing feature:**  
Inheritance throughout the library is a mess with a mix of super() calls and direct class instantiations.
All classes need to be looked after to make sure the Class.__init__() code is replaced by the rightful super().__init__() call.

**Expected behavior:**  
The library needs to behave exactly the same.

**Work to do:**  
Go through all the classes of all the modules to update the (multiple) inheritance calls.

**Comment by harshiniwho** [comment]
Hi! I can make this fix!

**Comment by arnauddupuis** [comment]
You sure can! Welcome on board ;)
