### ISSUE TITLE
Create a singleton out of Game

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#117]
**Problem summary/missing feature:**  
Game is a regular object, and we stayed away from making it a singleton for purely philosophical reasons. However, the game object is often a singleton for good reasons.

**Expected behavior:**  
The Game object should have an `instance()` method that returns a singleton object.

**Work to do:**  
The usual way of implementing a singleton pattern is to have a private constructor that is called by the instanciation constructor once, store the object in an instance variable and return that class variable in following calls to the constructor.
The problem is that we don't want to break the backward compatibility. Mostly because the need for multiple instance is either for the library internals or for more advanced case (a singleton would be useful in Suparex).
So I propose to have an instance() method that does the job of instanciating a Game object and store it into an `__instance` class variable and leave the constructor as it is right now. 
This way, if users require a singleton they use `instance()`, and if they don't they can continue to use `Game()`.

**Comment by RikilG** [comment]
Hey @arnauddupuis , I would like to work on this issue. Thanks!

**Comment by arnauddupuis** [comment]
Of course! Welcome on board!
I've assigned you to it.
If you need help on that I set up a Discord server, do not hesitate to join (the link is in the README_HACKTOBERFEST.md file).
