### ISSUE TITLE
Explore the replacement of Python list with numpy array for Board.

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#118]
**Problem summary/missing feature:**  
There's no way around it: `list` are slow. Particularly in our case. There's optimization that can be done and switching to C code is one of them.
For this first test, let's focus on engine.Board. 

**Expected behavior:**  
The Board object's interfaces and internals are expected to be the same (aside from data conversion specifics). 
The overall behavior is expected to be the same but hopefully faster.

**Work to do:**  
Convert Board._matrix and Board._overlapped_matrix to numpy array and make sure that all functions using the Board object works.

It would be wise to actually make a copy of Board (Board_v2) so we know it is an experimentation. Also, pgl-editor.py directly manipulates the internal matrix for resizing so this will cause massive issues if replaced.

It is possible to rename Board into Board_v1 and have a new Board object that morphs into one or the other, but it is really not a requirement.

If numpy is a valid improvement there will be following issues to migrate list that are intensily used within the library.

**Warning:** This is not a recommended issue for beginners as it requires spending some time understanding how Board works and the ramifications of a change in it.

**Comment by Frans06** [comment]
Assign It to me @arnauddupuis

**Comment by arnauddupuis** [comment]
Done!
Let's discuss this one on Discord, because I have ulterior motives ;)
I want this to be the base of the refactoring of the overlapping system.

**Comment by arnauddupuis** [comment]
Hi @Frans06,

Unfortunately, that one is kind of blocking so I am starting implementing that as I need it to convert the boards from 2D list to 3D numpy array.
So tell me if you have something I can hop on or else I'll re-affect that to myself as I have started to work on 3D maps.

**Comment by Frans06** [comment]
Yes, I got stuck at some point but almost nothing.

**Comment by arnauddupuis** [comment]
No problem at all, I can take over. It is not so simple, there's a lot of code (good and bad) in the Board object.

**Comment by Frans06** [comment]
closes #144
