### ISSUE TITLE
[BUG] in the editor the partial display viewport is not correctly restored.

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#122]
**Describe the bug**
When opening pgl-editor.py and loading a board, the partial display viewport is not correctly restored. 
The values (width and height) of the viewport are correctly saved but somehow, it is not correctly used. 

**To Reproduce**
1. In the editor, create a Board larger then 20 (like 50 of width)
2. Adjust the vieaport (Shift+V from the main menu).
3. Save the board and quit the editor.
4. Start the editor again and load the board.
5. See error: the viewport is no longer the one configured.

**Expected behavior**
The editor should always use the viewport's value from the last stored configuration at startup.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Python version 3.7.9

**Additional context**
To go the extra mile, we should actually save and load viewport per board and not globally.

**Comment by MChlebowski** [comment]
Hi. I would like to solve this issue but so far I haven't managed to reproduce the bug. Everytime I load the board I get the viewport that I set previously. Are you sure you haven't done any extra steps for this behavior?
I can fix problem with storing viewport globally, but right now I have no way of checking if the other problem is solved as well.

**Comment by arnauddupuis** [comment]
oh... that is weird!
I was certain that bug was still here... But you are right I reproduced it in older versions but not in the master. I might have been tired.
Sorry about that.
