### ISSUE TITLE
Create a "font" asset

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#123]
**Problem summary/missing feature:**  
The library could benefit from a font-like asset (located in pygamelib.assets). The idea came as I was participating in the olcCodeJam2020. I developed some sort of game and the title screen is built with a [Sprite](https://pygamelib.readthedocs.io/en/latest/gfx_core.html#pygamelib.gfx.core.Sprite) based on a font called 8BITS. It looks like that:
![Mytonica screenshot](https://img.itch.zone/aW1nLzQxOTY0MzEucG5n/315x250%23c/irOK97.png "Mytonica")

I thought that building an entire font like that could be good.

The source code for Mytonica is [here](https://github.com/arnauddupuis/mytonica) but please keep in mind that it is not a reference, it was done during a coding jam... And the sprite file is [here](https://github.com/arnauddupuis/mytonica/blob/master/gfx/mytonica.spr). 

**Expected behavior:**  
The font shall be a [SpriteCollection](https://pygamelib.readthedocs.io/en/latest/gfx_core.html#pygamelib.gfx.core.SpriteCollection) with indexes being the glyphs of the font.

For example:
```python
from pygamelib.assets import fonts

font_8bits = fonts.Pgl8Bits()
game.current_board().place_item( 0, 2, Tile(sprite=font_8bits['a']) )
```

**Work to do:**  
This requires to:

- [ ] Create a new fonts.py module in pygamelib.assets.
- [ ] Create a new Pgl8Bits class in fonts.py (or whatever better name you find).
- [ ] Create the sprites for the 26 letters of the alphabet (my initial thoughts on the size of the characters is 4 characters wide and 2 characters heights, this way it's a square).
- [ ] Create the sprites for the 10 numbers (from 0 to 9).
- [ ] Create the sprites for common punctuation (comma, dot, exclamation mark, etc.).
- [ ] Create the sprites for: +, -, *, /, =, (, ), [, ], { and }.
- [ ] Create the sprites for: #, &, -, _ and @.
- [ ] Write unit tests and coverage

Of course this is a suggestion for a minimum set. If you want to do more, you're welcome!

This task is probably better shared between more than one person (and it'll be a thousand times more comfortable when the sprite editor is actuially developped).

**Comment by Curious-Ujjwal** [comment]
I would like to work on this issue.
Please assign it to me.

**Comment by arnauddupuis** [comment]
You got it! 
Welcome on board. If you need help on that I set up a Discord server, do not hesitate to join (the link is in the [README_HACKTOBERFEST.md](https://github.com/arnauddupuis/pygamelib/blob/master/README_HACKTOBERFEST.md) file).

The work here is not especially hard, but as I did it for Mytonica it is a bit daunting without the Sprite editor.
It would be nice if other people wants to join and share the burden.
