### ISSUE TITLE
Add a display sprites capabilities to Screen

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#128]
**Problem summary/missing feature:**  
The [Screen object](https://pygamelib.readthedocs.io/en/latest/engine.html#pygamelib.engine.Screen) has a variety of functions to display things, but none to display a sprite.
For the moment, a sprite can only be displayed inside a board when attached to a complex item.

**Expected behavior:**  
The Screen object should be able to display a sprite on screen. This could be use for enriched dialogs, option screens, title screen etc.

**Work to do:**  
At least 2 methods should be added to Screen:

- [ ] display_sprite(sprite) that displays a sprite in parameter at the current cursor place.
- [ ] display_sprite_at(sprite, row, column) that displays the sprite in parameters at the row and column position. This means that the sprite needs to be displayed starting from its top left corner at (row, column) from (row, column) to (row + sprite.height, column + sprite.width)
- [ ] add the method documentation.
- [ ] add the relevant unit/coverage tests (reminder: code coverage must not diminish for a PR to be accepted)

In [Mytonica](https://github.com/arnauddupuis/mytonica), I had to do it so I have a draft implementation of `display_sprite_at()` :  
```python
# From Mytonica
def display_sprite_at(game, sprite, row, column):
    for r in range(0, sprite.size[1]):
        for c in range(0, sprite.size[0]):
            game.screen.display_at(
                sprite.sprixel(r, c), row + r, column + c,
            )
```
Obviously the reference to the Game object is useless and should be remove in that case (since it is only used to access to the Screen object).

**Comment by melsaa** [comment]
Hi, I'd like to work on this new feature

**Comment by arnauddupuis** [comment]
You got it, I assigned you to the issue.
We have a Discord server where we discuss issues and all, feel free to join: https://discord.gg/ZtVaMqr
