### ISSUE TITLE
Change the colored square and rectangle to their Sprixels counter part in the editor

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#129]
**Problem summary/missing feature:**  
Following issue #110, the full benefit of the Sprixel is not yet drawn for the color blocksin pgl-editor.py: it is still an ANSI string passed as the sprixel model.

**Expected behavior:**  
We should use the Sprixel methods that have the same result but with the added flexibility and capabilities of the Sprixel object.

**Work to do:**  
- [ ] Update the model chooser to use sprixels instead of strings.
- [ ] Make sure it is correctly handled by the wizzard.

**Comment by neil007m** [comment]
@arnauddupuis I notice this has the Hacktoberfest label but marked to do via automation - assuming not open then? (really cool project, would love to contribute)

**Comment by arnauddupuis** [comment]
Hi,
Thanks, I'm happy to provide work for you to contribute ;)

Yes, all issues added to the v1.3.0 project are automatically added to the TODO stage (see [here](https://github.com/arnauddupuis/pygamelib/projects/6)). I have already started to work on that one though.
All of these are core changes in the library's editor (pgl-editor.py) so we can develop a sprite editor and adds support for sprites in the item edition part of the editor.

I am adding issue along the way, I'll add more tomorrow but I'd like to code a little tonight ;)

Feel free to join the Discord server to exchange about all that: https://discord.gg/ZtVaMqr!

**Comment by neil007m** [comment]
Sounds good, I'll pick something up when it comes along. 
Happy coding!
