### ISSUE TITLE
Add a new path finding actuator that implements the A* algorithm

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#134]
**Problem summary/missing feature:**  
It would be nice to give the choice of pathfinding algorithms to the users. Right now actuators.PathFinder only implements the BFS algorithm.

**Expected behavior:**  
Add support for other popular pathfinding algorithms, in the case of that issue the A* algorithm.

**Work to do:**  
There's more than one way to do that **while maintaining backward compatibility**: 

1. Create a new actuators.PathFinderAStar actuator that copy PathFinder except for the `find_path()` method; or
2. Add a parameter to PathFinder's constructor to specify the algorithm (with BFS as default) and have `find_path()` to execute the right algorithm.

In my opinion, 2 is a better alternative, but there is design discussion here also:

1. The algorithm can be implemented in a private method (like `_find_path_bfs()` or `_find_path_astar()`) and `find_path()` calls the correct one based on the constructor parameter.
2. Less obvious, the `algorithm` (or `pf_algorithm` or `pf_algo` or any name you like) constructor's parameter could actually be a callable or a class (not instance) reference to an Algorithm.BFS or Algorithm.AStar and the `find_path()` method could take care of instantiating and running the algorithm.

I'm not so sure that the algorithm implementation would be that reusable so I would tend towards 1. But it is totally up for discussion.

In any case, the work looks like:

- [ ] Create a new class/method (depending on the chosen solution) that implements A*.
- [ ] Create a BFS counterpart and move the BFS pathfinding code from `find_path()` to the new entity (careful: not all the code in that method is for pathfinding). 
- [ ] Add the relevant parameters to PathFinder's constructor.
- [ ] add the methods documentation.
- [ ] add the relevant unit/coverage tests (reminder: code coverage must not diminish for a PR to be accepted)

**Comment by KRHero03** [comment]
Hi, I was thinking about the issue here.

I was thinking about implementing it using approach 2 specified by you, and providing a default parameter to find_path method, wherein the parameter will have a default value 0, which will use find_path_bfs and if the user passes 1, then the find_path will call find_path_astar. This will also maintain backward compatibility.

What do you think about it?

If you like it, I'll go ahead and implement it.

**Comment by KRHero03** [comment]
Also, it's really embarrassing but since I am new to contributing, how do I run the tests?

**Comment by arnauddupuis** [comment]
@KRHero03 thank you for your PR, I gave you some first feedback (prior to running the code). I'll do that tonight.
Please feel free to drop on Discord to discuss that or another issue: https://discord.gg/ZtVaMqr
