### ISSUE TITLE
inventory_space() misses a setter

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#142]
**Problem summary/missing feature:**  
board_items.Immovable implements the `inventory_space()` method but there is no setter and users needs to use the private variable (undocumented).

**Expected behavior:**  
We need an easy and documented way to set inventory space after construction.

**Work to do:**  
transform `inventory_space()` into a `@property` that manages the private variable `_inventory_space`.

**Comment by morrme** [comment]
What is your deadline for this task?

**Comment by arnauddupuis** [comment]
I don't have any, this is not a big one and we can help if you come on the discord server.
I would like to make a release in November to thank all the contributors from Hacktoberfest.

**Comment by morrme** [comment]
That is very kind of you! I forgot all about Hacktoberfest! 

Feel free to assign this to me. I will give you an update by the end of the week.

**Comment by arnauddupuis** [comment]
You got it!
If you need any help or want to discuss the discord server is here: https://discord.gg/ZtVaMqr
