### ISSUE TITLE
Create a Color class

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#145]
**Problem summary/missing feature:**  
At the moment, the main user of colors is the Sprixel class. However, since we use the `blessed.Terminal` class to display the colors, it is always the user's responsibility to correctly use and know the right functions in blessed.

**Expected behavior:**  
All colors should use a unique `Color` class. This means that instead of declaring a Sprixel like that:
```python
sprix = Sprixel( '[]', terminal.on_color_rgb(123, 55, 0), terminal.color_rgb(0,0,0) )
```
The use should be able to do:
```python
sprix = Sprixel( '[]', Color(123, 55, 0), Color(0,0,0) )
```

**Work to do:**  

- [x] Create a Color class (probably in gfx.core) that supports RGB.
- [ ] Change the behavior of Sprixel to make sure that the bg_color and fg_color use and store a Color.
- [ ] Change the rendering of Sprixel to translate the `Color` to the correct `blessed.Terminal` call.
- [ ] Convert the export/import of a Sprixel (or anything that uses Color) particularly the board and sprites import/export systems.

As a first bonus we could support RGBa (a for alpha). The `a` parameter is a float between 0 and 1 and controls the blending with the background (we cannot really support transparency in the terminal). This requires the implementation of a `blend(Color)` method that returns a new color blended with the one in parameter.

As a second bonus we could support RGB and HSV color spaces (but this is not required for a first implementation).

**Comment by desikan95** [comment]
Hi @arnauddupuis I'd like to take this up.

**Comment by arnauddupuis** [comment]
I'm sorry I assigned it to myself because I need it for the particle system and need it quickly. It's almost done.
The color class is done and I'm integrating it everywhere already.

**Comment by desikan95** [comment]
Hey no issues. I'm new to open source development and came across this repo while looking for projects to contribute. In case there's a task that doesn't need to be completed urgently, feel free to assign it to me. Thanks ! :+1:

**Comment by arnauddupuis** [comment]
Sure, you could take issue #141 it's a good first issue to get to know the code. 
It's in the editor so, no messing with the library directly. It's not a very difficult one and with a limited scope it can get you up and running on the project (tests, coverage, flake8 and black to name a few).

To be honnest, the Color class is a trap. This breaks so many things it is not at all new coders friendly. I hugely underestimated the ramifications (look at that branch https://github.com/arnauddupuis/pygamelib/tree/arnauddupuis/issue145 and try to run the tests for fun...).

**Comment by desikan95** [comment]
Sure ! Thanks. I'll work on it and reach out to you in case I have any questions.
