### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by arnauddupuis** [arnauddupuis/pygamelib#5]
This entire project completely lacks unit tests.

Please reference this issue in PR. 

This issue will be closed when all modules have unit tests for all methods.

**Comment by grimmjow8** [comment]
Started hacking away at some of these.

**Comment by arnauddupuis** [comment]
Cool! Thanks a lot!
Do not hesitate if you find design flaws or error in the code, I'm still fairly new to Python.

**Comment by arnauddupuis** [comment]
Current coverage: 97.87%.
I'm closing the issue.
